version: '3.8'

services:
  # Servicio 1: Servidor Web / Backend Node.js
  aroma-web-app:
    build: .
    container_name: aroma_cacao_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always

  # Servicio 2: Servidor Proxy Inverso Nginx
  aroma-proxy:
    image: nginx:alpine
    container_name: aroma_cacao_nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aroma-web-app